apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: kustomization
metadata: 
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceref: 
    kind: GitRepository
    name: flux-system
  path: ./apps/dev
  prune: true
  wait: true
  timeout: 5m0s